// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
#pragma once

// X-Macro for defining all arguments in one place
// Format: ARGUMENT(EnumName, Name, Alias, Desc, DataType, Kind, Visibility, Required, CountLimit, Category, ExclusiveSet)
// Note: DataType is wrapped in parentheses to handle types with commas (e.g., std::vector<T>)
#define WSLC_ARGUMENTS(_) \
_(All,            "all",             L'a',           L"Select all the running containers",                         (bool),                       Kind::Standard,    Visibility::Usage,   false,  1, Category::None, ExclusiveSet::None) \
_(AllPrune,       "all",             L'a',           L"Remove all unused images not referenced by any container",  (bool),                       Kind::Standard,    Visibility::Usage,   false,  1, Category::None, ExclusiveSet::None) \
_(AllVolumes,     "all",             L'a',           L"Delete all volumes",                                        (bool),                       Kind::Standard,    Visibility::Usage,   false,  1, Category::None, ExclusiveSet::None) \
_(Attach,         "attach",          L'a',           Localization::WSLCCLI_AttachArgDescription(),                 (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(CIDFile,        "cidfile",         NoAlias,        L"Write the container ID to the provided path.",              (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(ContainerId,    "container-id",    NoAlias,        Localization::WSLCCLI_ContainerIdArgDescription(),            (std::wstring),               Kind::Positional,  Visibility::Help,     true,  1, Category::None, ExclusiveSet::None) \
_(ContainerIdOpt, "container-id",    NoAlias,        Localization::WSLCCLI_ContainerIdArgDescription(),            (std::wstring),               Kind::Positional,  Visibility::Help,    false, 10, Category::None, ExclusiveSet::None) \
_(ContainerIdReq, "container-id",    NoAlias,        Localization::WSLCCLI_ContainerIdArgDescription(),            (std::wstring),               Kind::Positional,  Visibility::Help,     true, 10, Category::None, ExclusiveSet::None) \
_(DNS,            "dns",             NoAlias,        L"IP address of the DNS nameserver in resolv.conf",           (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(DNSDomain,      "dns-domain",      NoAlias,        L"Set the default DNS Domain",                                (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(DNSOption,      "dns-option",      NoAlias,        L"Set DNS options",                                           (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(DNSSearch,      "dns-search",      NoAlias,        L"Set DNS search domains",                                    (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Detach,         "detach",          L'd',           L"Run a process inside the container and detach from it",     (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Entrypoint,     "entrypoint",      NoAlias,        L"Specifies the container init process executable",           (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Env,            "env",             L'e',           L"Key=Value pairs for environment variables",                 (std::wstring),               Kind::Standard,    Visibility::Help,    false, 10, Category::None, ExclusiveSet::None) \
_(EnvFile,        "env-file",        NoAlias,        L"File containing key=value pairs of env variables",          (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(ForceD,         "force",           L'f',           L"Delete containers even if they are running",                (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Format,         "format",          NoAlias,        L"Output formatting (json or table) (Default:table)",         (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(ForwardArgs,    "arguments",       NoAlias,        L"Arguments to pass to container's init process",             (std::vector<std::wstring>),  Kind::Forward,     Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(ForwardArgsP,   "process arguments", NoAlias,      L"Arguments to pass to command to be run inside the container", (std::vector<std::wstring>),Kind::Forward,     Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(GroupId,        "groupid",         NoAlias,        L"Group Id for the process",                                  (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Help,           "help",            WSLC_HELP_CHAR, Localization::WSLCCLI_HelpArgDescription(),                   (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(ImageId,        "image",           NoAlias,        L"Image name",                                                (std::wstring),               Kind::Positional,  Visibility::Help,     true,  1, Category::None, ExclusiveSet::None) \
_(ImageIdReq,     "image",           NoAlias,        L"Image name",                                                (std::wstring),               Kind::Positional,  Visibility::Help,     true, 10, Category::None, ExclusiveSet::None) \
_(Info,           "info",            NoAlias,        Localization::WSLCCLI_InfoArgDescription(),                   (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Interactive,    "interactive",     L'i',           Localization::WSLCCLI_InteractiveArgDescription(),            (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Input,          "input",           NoAlias,        L"Path to the tar archive file containing the image.",        (std::wstring),               Kind::Standard,    Visibility::Help,     true,  1, Category::None, ExclusiveSet::None) \
_(Label,          "label",           NoAlias,        L"Volume metadata setting",                                   (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Name,           "name",            NoAlias,        L"Name of the container",                                     (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(NoDNS,          "no-dns",          NoAlias,        L"No configuration of DNS in the container",                  (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Opt,            "opt",             NoAlias,        L"Set driver specific options.",                              (std::wstring),               Kind::Standard,    Visibility::Help,    false, 10, Category::None, ExclusiveSet::None) \
_(Output,         "output",          L'o',           L"Path for the saved image.",                                 (std::wstring),               Kind::Standard,    Visibility::Help,     true,  1, Category::None, ExclusiveSet::None) \
_(PasswordStdin,  "password-stdin",  NoAlias,        L"Obtain the password from stdin",                            (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Progress,       "progress",        NoAlias,        L"Progress type (format: none|ansi) (default: ansi)",         (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Publish,        "publish",         L'p',           L"Publish a port from a container to host",                   (std::wstring),               Kind::Standard,    Visibility::Help,    false, 10, Category::None, ExclusiveSet::None) \
_(Pull,           "pull",            NoAlias,        L"Image pull policy (always|missing|never) (default:never)",  (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Quiet,          "quiet",           L'q',           L"Outputs the container IDs only",                            (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Registry,       "registry",        NoAlias,        L"Name of the registry server",                               (std::wstring),               Kind::Positional,  Visibility::Usage,    true,  1, Category::None, ExclusiveSet::None) \
_(Remove,         "remove",          L'r',           L"Remove the container after it stops",                       (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Scheme,         "scheme",          NoAlias,        L"Use this scheme for registry connection",                   (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Server,         "server",          NoAlias,        L"Registry server name",                                      (std::wstring),               Kind::Positional,  Visibility::Usage,    true,  1, Category::None, ExclusiveSet::None) \
_(SessionId,      "session",         NoAlias,        Localization::WSLCCLI_SessionIdArgDescription(),              (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(SignalK,        "signal",          L's',           L"Signal to send (default: SIGKILL)",                         (std::wstring),               Kind::Standard,    Visibility::Usage,   false,  1, Category::None, ExclusiveSet::None) \
_(SignalS,        "signal",          L's',           L"Signal to send (default: SIGTERM)",                         (std::wstring),               Kind::Standard,    Visibility::Usage,   false,  1, Category::None, ExclusiveSet::None) \
_(Size,           "size",            L's',           L"Size of the volume in bytes. Suffixes (K, M, G, T, or P)",  (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Source,         "source",          NoAlias,        L"Current or existing image in the image-name[:tag] format",  (std::wstring),               Kind::Positional,  Visibility::Usage,    true,  1, Category::None, ExclusiveSet::None) \
_(Target,         "target",          NoAlias,        L"New name for the image in the image-name[:tag] format",     (std::wstring),               Kind::Positional,  Visibility::Usage,    true,  1, Category::None, ExclusiveSet::None) \
_(Time,           "time",            L't',           L"Time in seconds to wait before executing (default 5)",      (std::wstring),               Kind::Standard,    Visibility::Usage,   false,  1, Category::None, ExclusiveSet::None) \
_(TMPFS,          "tmpfs",           NoAlias,        L"Mount tmpfs to the container at the given path",            (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(TTY,            "tty",             L't',           L"Open a TTY with the container process.",                    (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(User,           "user",            L'u',           L"User ID for the process (name|uid|uid:gid)",                (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(UserName,       "username",        L'u',           L"Username for the registry connection",                      (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Verbose,        "verbose",         L'v',           L"Output verbose details",                                    (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Virtual,        "virtualization",  NoAlias,        L"Expose virtualization capabilities to the container",       (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(Volume,         "volume",          NoAlias,        L"Bind mount a volume to the container",                      (std::wstring),               Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None) \
_(VolumeNameC,    "name",            NoAlias,        L"Name to give to teh volume",                                (std::wstring),               Kind::Positional,  Visibility::Help,     true,  1, Category::None, ExclusiveSet::None) \
_(VolumeNameD,    "names",           NoAlias,        L"Names of the volumes to delete",                            (std::wstring),               Kind::Positional,  Visibility::Help,    false, 10, Category::None, ExclusiveSet::None) \
_(VolumeNameI,    "names",           NoAlias,        L"Names of the volumes to inspect",                           (std::wstring),               Kind::Positional,  Visibility::Help,     true, 10, Category::None, ExclusiveSet::None) \
_(TestArg,        "arg",             L'a',           L"Shows Ninjacat",                                            (bool),                       Kind::Standard,    Visibility::Help,    false,  1, Category::None, ExclusiveSet::None)
