/*++

Copyright (c) Microsoft. All rights reserved.

Module Name:

    wslcsdk.idl

Abstract:

    This file contains the definition of a WinRT projection of the WSL Container SDK API.

--*/

namespace Microsoft.WSL.Containers
{
    runtimeclass SessionSettings
    {
        SessionSettings(String name, String storagePath);

        String Name { get; };
        String StoragePath { get; };

        UInt32 CpuCount { get; set; };
        UInt32 MemoryMb { get; set; };
        UInt32 TimeoutMS { get; set; };
        VhdRequirements VhdRequirements { get; set; };
        SessionFeatureFlags FeatureFlags { get; set; };
    };

    runtimeclass Session
    {
        static Session Create(SessionSettings settings);

        void Terminate();
    };

    [flags]
    enum SessionFeatureFlags
    {
        None = 0x00000000,
        EnableGpu = 0x00000004
    };

    enum VhdType
    {
        Dynamic = 0,
        Fixed = 1,
    };

    runtimeclass VhdRequirements
    {
        VhdRequirements(String name, UInt64 sizeInBytes, VhdType type);

        String Name { get; };
        UInt64 SizeInBytes { get; };
        VhdType Type { get; };

        // Sets the POSIX owner uid and gid that the volume root will be chowned to
        // after creation. Both values are set together to avoid half-configured ownership.
        // Has no effect when called on a VhdRequirements used with the session rootfs VHD.
        void SetOwner(UInt32 uid, UInt32 gid);

        // Sets the POSIX mode bits (e.g. 0o750) that the volume root will be chmoded to
        // after creation. Maximum legal value is 07777 (decimal 4095); larger values are
        // rejected by the service. Has no effect when called on a VhdRequirements used
        // with the session rootfs VHD.
        void SetMode(UInt32 mode);
    };
}