# Publishes the release NuGet packages to nuget.org.
parameters:
  - name: bypassTests
    type: boolean
    default: false

  - name: packages
    type: object
    default:
      - Microsoft.WSL.PluginApi
      - Microsoft.WSL.Containers

stages:
  - stage: nuget_publish
    displayName: Publish nuget packages
    dependsOn:
      - package
      - ${{ if eq(parameters.bypassTests, false) }}:
          - test
    variables:
      ob_release_environment: Production
    jobs:
      - ${{ each package in parameters.packages }}:
          - job: nuget_${{ replace(package, '.', '_') }}
            displayName: Push ${{ package }} to NuGet.org
            pool:
              type: release
              os: windows

            variables:
              nugetPath: $(Pipeline.Workspace)\package\nuget

            templateContext:
              inputs:
                - input: pipelineArtifact
                  artifactName: drop_wsl_package
                  targetPath: $(Pipeline.Workspace)\package
                  itemPattern: nuget/${{ package }}.*.nupkg

            steps:
              - task: NuGetCommand@2
                displayName: Push ${{ package }}
                inputs:
                  command: push
                  packagesToPush: $(nugetPath)\${{ package }}.*.nupkg
                  nuGetFeedType: external
                  publishFeedCredentials: wsl-nuget-publish
