trigger:
  branches:
    include:
    - master
    - release/*

stages:
- template: build-stage.yml@self
  parameters:
    isRelease: false
    pool:
      vmImage: windows-2025-vs2026
    clangFormat: 'C:\Program Files\LLVM\bin\clang-format.exe'
    vsoOrg: shine-oss
    vsoProject: wsl

- template: test-stage.yml@self
  parameters:
    includePackageStage: false
    rs_prerelease_only: true
    pool: server
