trigger:
  branches:
    include:
    - master
    - release/*

variables:
  WindowsContainerImage: "onebranch.azurecr.io/windows/ltsc2022/vse2022:latest"
  WindowsHostVersion: '1ESWindows2022'

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/Microsoft.NonOfficial.yml@templates
  parameters:
    platform:
      name: "windows_undocked"
    featureFlags:
      EnableCDPxPAT: false
      WindowsHostVersion: 1ESWindows2022
    globalSdl:
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.gdnsuppress
        suppressionSet: default
      apiscan:
        enabled: false
      credscan:
        enabled: true
      perStage:
        credscan:
          enabled: true
      policheck:
        enabled: true
        break: true
        severity: Note
    git:
      fetchDepth: -1
      fetchTags: true

    stages:
    - template: build-stage.yml@self
      parameters:
        isRelease: false

    - template: test-stage.yml@self
      parameters:
        rs_prerelease_only: true
