name: Validate distributions

on:
  pull_request:
    paths: ['distributions/**']
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  check:
    name: Validate distributions
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
          
        - name: Run validation
          run: python distributions/validate.py distributions/DistributionInfo.json
          shell: bash
