name: Process new issue

on:
  workflow_dispatch :
  issues:
    types: [opened]

jobs:
  wti:
    name: Run wti
    runs-on: windows-2022
    permissions:
      issues: write
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - uses: ./.github/actions/triage
      with: 
        issue: "${{ github.event.issue.number }}"
        token: ${{ secrets.GITHUB_TOKEN }}